##后台JS语言
INSERT INTO met_language VALUES (null, 'app_shop_ok', "Yes", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cancel', "No", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_save', "Save", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_operatorok', "Operation successful", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_saveok', "Save Successful", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_delok', "Deleted successfully", 1, 1, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_del', "Delete", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_deled', "deleted", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_deling', "Deleting...", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_deleteok', "Still delete it?", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_clear', "Delete", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_close', "Close", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_operator', "Operating", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_menager', "Management", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_addto', "Add", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_editor', "Edit", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_select_all', "Select all", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_select', "Select", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_selected', "Selected", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_select_able', "Optional", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_show_open', "Expand", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_show_modify', "Modify", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_setting', "Settings", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_buy', "Purchase", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_js_tips1', "At least select one option", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_js_tips2', "A positive number indicates a price increase/A negative number indicates a price reduction", 1, 0, 1, 10043, 'en');
##运费模板
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips1', "Don\'t support international logistics inquiry", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips2', "The text was not found", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips3', "At least enable one payment method", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips4', "Processing，please be patient to wait", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips5', "zone", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips6', "Processing，please be patient to wait.", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips7', "Once deleting the area, the subordinate zone of the zone will also be deleted. Are you sure to delete them?", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips8', "Are you sure to delete the shipping template?", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_country', "Country", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_set_distr_area', "Add shipping zone", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_table_row1', "Shipping zone", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_table_row2', "Per order/piece", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_table_row3', "Shipping fee", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_table_row4', "Plus（piece）", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_table_row5', "Recharge", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add_subarea', "Increase sub-zone", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_package_tips1', "All have been consumed, please continue", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_package_tips2', "Purchase", 1, 0, 1, 10043, 'en');
##setting
INSERT INTO met_language VALUES (null, 'app_shop_guest', "Guest", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_save_success_tips1', "Save successful", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_login_tips1', "You haven\'t logged in,please", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_login_tips2', "Log in background", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_login_tips3', ",refresh the page again", 1, 0, 1, 10043, 'en');
##week
INSERT INTO met_language VALUES (null, 'app_shop_mom', "Monday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_tues', "Tuesday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_wed', "Wednesday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_thur', "Thursday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_fri', "Friday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_sat', "Saturday", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_sun', "Sunday", 1, 0, 1, 10043, 'en');
##goods
INSERT INTO met_language VALUES (null, 'app_shop_goods_tips1', "Don\'t add the same specification", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_tips2', "Preset more specification value", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_tips3', "Only add up to three specifications", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_tips4', "Enter number", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_tips5', "Inventory can\'t be empty", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_toadd', "+add", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_table_row1', "Standard price", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_table_row2', "Inventory", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_table_row3', "Sales", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_table_row4', "Picture", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_price', "Price", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_stock', "Inventory", 1, 0, 1, 10043, 'en');
##spec
INSERT INTO met_language VALUES (null, 'app_shop_spec_tips1', "After deleting specification，Specification value will also be delete，still delete it?", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spec_input_tips1', "Enter specification value", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spec_value', "Specification value", 1, 0, 1, 10043, 'en');
###后台语言
INSERT INTO met_language VALUES (null, 'app_shop_not_null_tips', "Can\'t be empty", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_price_set', "Price Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_decimal_len', "decimal places", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_price_set_type', "Price settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_price_type1', "Uniform price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_price_type2', "Set according to member group", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_user_group_set', "Member Group Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_more', "Advanced Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_user_gdiscount', "Member discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_web_hidden', "Hidden in front desk", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_timing_release', "Publish on time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_tocom', "Recommend", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_totop', "Place to top", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_sold_out', "Sold out", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shipping_code', "Set Shipping code", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_detail', "Card details", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_back', "Return", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_vgoods_info', "Virtual product information record", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_vgoods_set', "Virtual product information settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_serial_number', "Shipping code", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_grantable', "Send or not", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_addtime', "Add time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_granttime', "Automatically send", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_grant_user', "Buyer", 1, 0, 0, 10043, 'en');
##优惠与折扣
INSERT INTO met_language VALUES (null, 'app_shop_all', "All", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_coupon', "Coupons", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_edit', "Edit Coupons", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_add', "New Coupons", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_name', "Coupons Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_price', "Value", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_condition', "Condition of Use", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_use_tips1', "Amout is only more than", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_use_tips2', ",It is used", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_suer_limit', "Limit User", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_suerable', "Member can get coupons.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_suerable1', "can get coupons.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_total_amount', "Total", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_zhang', "piece", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_begin_time', "Start time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_end_time', "End time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_create_time', "Create time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_include_good', "Valid for", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_all_good', "All Products", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_appoint_good', "Some Products", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_use_script', "Instructions", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_select_goods', "Select product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_goods_editor', "Edit product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_selected', "Selected", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_unselected', "Unselected", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_limit_collar', "Everyone only get", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_tips1', "Total quantity must be larger than limit quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_goods_name', "Product Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_goods', "Product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_select_all', "Select all", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_unselect_all', "Unselect all", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_not_begining', "Not Start", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_runing', "Processing", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_end', "Completed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_restriction', "Limit", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_term_of_validity', "Valid", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_table_title1', "Received / Used / Total", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_state', "Status", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_state1', "Processing", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_state2', "Not Start", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_state4', "Completed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_set_price', "Price Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_sale', "Discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_sale_goods_num', "According to order quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_sale_static', "Price reduction", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_discount', "Discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_amount', "Quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_static_discount', "Fixed discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_order_free', "Buyer order any product,money off", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_table_row1', "No limit", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_table_row2', "Person", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_table_row3', "to", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_data_error', "Data error", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount_error1', "End time must be larger than start time.", 1, 0, 0, 10043, 'en');

##运费模板
INSERT INTO met_language VALUES (null, 'app_shop_freight_temp_name', "Shipping template name(Such as:for American.Required field cannot be empty)", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_distribution_area', "Shipping zone", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add_distribution_area', "Add new shipping zone and costs", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_first_piece', "Per order/piece", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_continued', "Plus（piece）", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_freight', "Shipping fee", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_renew', "Recharge", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_reftemp_set', "Shipping Templates-Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add_ftemp', "Add a new shipping template", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add_area', "Add shipping zone", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_select_area', "Select shipping zone", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_pselect', "Select", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add', "Add", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_refresh_area', "Update（after adding new data,please click to update）", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_add_country', "Country", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips9', "Select the zones with same shipping cost.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight_tips10', "Enter zone name,Press the Enter key to add more zones.", 1, 0, 0, 10043, 'en');
##goods
INSERT INTO met_language VALUES (null, 'app_shop_goods_manager', "Products Management", 1, 0, 0, 10043, 'en');
##order_head
INSERT INTO met_language VALUES (null, 'app_shop_head_shop_module', "Mall module", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_order_survey', "Order Overview", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_order_all', "All Order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_set', "Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_help', "Help", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_order_reminding', "Order Reminder", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_financial_details', "Transaction Records", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_goods_manager', "Products Management", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_discount', "Coupons and Discounts", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_coupon', "Coupons", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_order', "Order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_head_application', "Application", 1, 0, 0, 10043, 'en');
##order
INSERT INTO met_language VALUES (null, 'app_shop_order_plac_order', "Order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_pay', "Pay", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_deliver', "Shipping", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_complete', "Complete order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_not_logistics', "Needn\'t to shipping", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_info', "Shipping information", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_progress', "Delivery progress", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_no', "Order Number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_pay_type', "Payment Method", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_buyer', "Buyer", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_distribution_mode', "Shipping method", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_express_delivery', "Shipping by express", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_address_info', "Receipt information", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_invoice_info', "Invoice information", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_buyer_message', "Buyer Message", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_business_notes', "Seller Remarks", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_return_message_record', "Message about return", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_reply', "Reply", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_close_tips1', "The order will be", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_close_tips2', "automatically close", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_goods_name', "Product Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_unit_price', "Price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_amount', "Quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_freight', "Shipping fee", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_subtotal', "subtotal", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_view_goods_detail', "View product details", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_amount_price', "Order sum", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_discount', "discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_price_rise_down', "Price increase/reduction", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_real_payment', "Order Amount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_need_logistics', "Need to shipping", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_receiving_address', "Shipping Address", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_company', "shipping company", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_tips1', "add a shipping method", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_tips2', "Add a logistics compay", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_tips3', "Please enter a valid tracking number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_logistics_no', "Tracking number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_price_modify', "Modify price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_close', "Close order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_complete', "Complete order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refunds', "Complete refund", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_income', "Income", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_income_tips1', "Last month", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_income_tips2', "Compare with last month", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_count', "Order Quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_plac_order_user_num', "Ordered buyers", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_today', "Today", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_week', "This Week", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_month', "This Month", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_all', "All Order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_pending_papy', "Waiting for payment", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_pending_delivery', "Waiting for shipment", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_already_shipped', "Delivering", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_conplete', "Completed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_closed', "Closed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_no_usernaem', "Order number、member name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_screening_exporting', "Filter and Export", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_exporting', "Export", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_to', "to", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_export_option', "Export options", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_number', "Quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_username', "Member Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_time', "Order Time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state', "Status", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_goods', "Product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund', "Returns and Exchanges", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_deny_refund', "Refuse returns and exchanges", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_cancel_reason', "Reason of cancel", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund_reason', "reason of return", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_reason_detail', "Reason", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_click_show_detail', "More", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_closeok', "Are you sure to close the order?", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_complateok', "Are you sure to set the order as completed order?", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund_denyok', "Are you sure to refuse refunding/returning for this order?", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund_conplateok', "Are you sure to set as completing refund for this order?", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund_conplate_tips', "This operation does not automatically generate refund records, please manually add income & expenditure record in the “Transaction Records”", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_count_tips1', "Total", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_count_tips2', "pieces", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_item', "piece", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_invoice', "Invoice", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_select_logistics', "Select shipping company", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_closed', "Order is closed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_price_modifyok', "Modified price successfully", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_buyok', "Complete order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_comment_modifyok', "Modified successfully", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_error_tips1', "No products or beyond purchase limit", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_sendok', "Complete shipping", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state0', "Closed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state1', "Waiting for payment", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state2', "Waiting for shipment", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state3', "Delivering", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state4', "Completed", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state5', "Refunding", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_state6', "Refund because of no product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_paymethod1', "Pay when receiving items.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_paymethod2', "Pay via company\'s bank card", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_order_paymethod3', "Other payment method", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row1', "Product name*quantity", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row2', "Member Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row3', "Order Time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row4', "Status", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row5', "Order Amount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row6', "Shipping Address", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row7', "Buyer Message", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_xport_row8', "Seller Remarks", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nogoods', "Refund because of no stock", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund', "Refunding…", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_closed', "Closed", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_bepaid', "waiting for payment", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_bedeliver', "Pending", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentcod', "pay when receiving item", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_company_pay', "pay with company bank card", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_over_deliver', "Shipped", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_over', "Completed", 0, 0, 1, 10043, 'en');
##product
INSERT INTO met_language VALUES (null, 'app_shop_product_tips1', "After modifing", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_tips2', "Customer needn\'t to set a delivery address", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_tips3', "0 is no limit", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_tips4', "Please set in Mall-Settings，open", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_tips5', "After completing settings and close pop-ups，click\"Update specification\" button,then add a specification/specification value.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_table_title', "Specification / Price / Inventory", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_goods_specification', "Product specification", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_select_spec', "Select a specification", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_input_spec_name', "Enter specification name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_goods_stock', "Product Inventory", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_price', "Price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_original_price', "Original price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_show_goods_stock', "Display the product inventory in the page", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_logistics_other', "logistics/other", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_freight_set', "Shipping Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_unified_freight', "Flat rate", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_temp_freight', "Shipping template", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_create', "Add new", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_refresh', "Refresh", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_not_logistics', "Need no logistics", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_message_set', "Leave a message", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_add_field', "+add fields", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_field_name', "Fields name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_multiline', "Mutil line", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_required', "Can\'t be empty", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_restrictions', "Purchase limit", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_user_discount', "Member discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_not_discount', "Can\'t be empty", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_invoice', "Invoice", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_exist', "exist", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_not_exist', "Not exist", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_vgoods_delivery', "Automatically delivery virtual goods", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_vgoods_delivery_open', "Open the function and save product,then set a automatic shipping code in product management list page", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_publish', "Add a product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_search', "Search", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_product', "Product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_price', "Price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_hits', "Views", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_stock', "Inventory", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_stock', "Inventory", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_total_sales', "Total sales", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_update_time', "Update Time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_search_option1', "Status", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_search_option2', "Hidden in front desk", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_search_option3', "Recommend", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_search_option4', "Sold out", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_order_by', "Order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_product_order_by_tips1', "The larger value ,the more forward position", 1, 0, 0, 10043, 'en');
##商场规格设置
INSERT INTO met_language VALUES (null, 'app_shop_spec_more', "Preset more specification", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spec_setting', "Specification preset", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spec_refresh', "Update specification", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_specification_setting', "Specification library management-Mall", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_tips1', "Enter specification name", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_tips2', "Enter specification value", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_tips3', "After adding a [Specification/Specification Value], you must modify the [Specification Name/Specification Value] ,then can add the next [Specification/Specification Value]; after modification, the mouse leaves the input box and clicks any area of the page or press Enter key to save it.", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_management', "Specification library management", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_name', "Specification name", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_value', "Specification name", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_value_add', "Add Specification value", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_spce_add', "Add Specification", 1, 0, 1, 10043, 'en');
##自动发货码
INSERT INTO met_language VALUES (null, 'app_shop_card_manager', "Products Management", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_table_row1', "Specification group", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_table_row2', "Total / Sent / Used /Sending", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_table_row3', "Sending", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_table_row4', "Sent", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_table_row5', "Used", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_add_card', "Add shipping codes", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_tips1', "Enter shipping code,press Enter key to enter more", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_title_modify', "Modify", 1, 0, 0, 10043, 'en');
##邮件通知
INSERT INTO met_language VALUES (null, 'app_shop_remind_title', "Admistrator Reminder-Order Reminder", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips1', "If buyer paid,remind adminitrator to deliver product", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips2', "Set mutiple", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips3', "Enter phone number，then save it.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips4', "Note: If  want to enable email and SMS reminder, first need to add an email address and open SMS function.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_phone_number', "Phone number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_mail', "Email Address", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_userremind', "Reminder for buyer", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_adminremind', "Reminder for administrator", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_user_title', "User Reminder -Order Reminder", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips5', "Firstly set [outbox] and [SMS] function", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips6', "Settings-General-Mail Sending Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips7', "「SMS」My Applications-SMS Function", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_tips8', "Variable parameters, If add the following parameters to the reminder content,this parameters will automatically change.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_ordernum', "-Order number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_suername', "-Member Name", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_logistics', "shipping company", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_courier_number', "Delivery number", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_ordered', "Added to cart", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_payed', "paid", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_send', "Shipped", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_short_message_reminding', "SMS reminder", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_message_set', "SMS Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_short_mail_reminding', "Email reminder", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_mail_set', "Email Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_mail_title', "Title", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_mail_content', "Contents", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_reminding', "SMS reminder", 1, 0, 0, 10043, 'en');
##设置
INSERT INTO met_language VALUES (null, 'app_shop_set_basic_setting', "General", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_pay_setting', "Payment", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_temp_freight_setting', "Shipping template", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_setting', "Price", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_discount_setting', "Discount", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_switch', "Mall Swtich", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips1', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips2', "This function is only used for China business company,please ignore it.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips3', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips4', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips5', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips6', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips7', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips8', "Checkout as Guest，need no register.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips9', "Buyer can cancel orders before delivering products.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips10', "The reason of canceling orders（Click", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips11', "The reason of returns and exchanges（Click", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips12', "Once added a product to cart,reduce inventory quantity.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips13', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips14', "Log in by registered or social account", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips15', "Need to set in", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_tips16', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_guest_mod', "Checkout as Guest", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_second', "", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_logistics_tracking', "Shipping tracking", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_cancel_order', "Cancel orders", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_refund_order', "Function of returns and exchanges", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_refund_hints', "Reminder contents", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_stock_type', "Inventory Change Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_show_goods_order', "Rule of displaying recommend products", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_goods_detail', "Product details page", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_goods_select', "Recommend products", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_goods_all_goods', "All product in the same product category", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_com_goods', "Recommended product in mall settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_module_com_goods', "Recommended products in product management settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_sort_rule', "Sort Rule", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_by_module', "Order by column settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_by_hits', "Order by clicks", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_by_update_time', "Order by update time", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_show_goods_amount', "，quantity of displaying", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_show_cart_page', "Cart page", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_shop_all_goods', "All products in Mall", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_state_auto', "Order status", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_close', "Close order", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_close_tips', "minutes，automitical close the order if add a product to cart but no paid.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_complete', "Automatically complete orders", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_complete_tips', "days, the shipped order will be automatically classified as completed orders", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_delete', "Automatically delete orders", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_order_auto_delete_tips', "days，delete the closed orders.", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_invoice_setting', "Invoice Settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_plain_invoice', "Invoice", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_invoice_able', "If open it,buyer can ask a invoice", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_invoice_content', "Invoice contents", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_logistics_package', "Logistics service", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_logistics_table_title1', "Price/ USD", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_logistics_table_title2', "Consumption / times", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_account_login', "Application account login", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_payapi_setting', "Payment interface settings", 1, 0, 0, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentcod', "Pay when receiving items.", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentonline', "Pay online", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentmod', "Payment method", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_default_setting', "Price settings", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_unified_price', "Uniform price", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_by_group', "Set according to member group", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_group_setting', "Member Group Settings", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_setting_example', "Such as 0.8", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_set_price_zhe', "Discount", 1, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shopv2_para_search', 'Selection of commodity list parameters', '1', '0', '0', '10043', 'en');
INSERT INTO met_language VALUES (null, 'app_shopv2_para_search_tips', 'Use to filter the mall parameters (requires foreground template support)', '1', '0', '0', '10043', 'en');