INSERT INTO met_language VALUES (null, 'app_shop_guest_login', "Go on as guest", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_favorite_fail', "Failture", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_favorite_ok', "Successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nofavorites', "No favorites", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_favorite_expired', "expired", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_favorited', "favorites", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_favorite_add', "add to favorites", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receiveok', "Successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_canuser', "Can be used", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receive_fail', "Failture", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_immediate_use', "Use now", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_immediate_receive', "Get now", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_sheet', "piece", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receivelimit', "each person only can get", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_selectgoods_use', "You can use coupons for the items", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nodiscounts', "No coupons that meet the requirements", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_overtime', "expired", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_used', "Used", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receive', "Not received", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_received', "Received", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discountname', "coupons name", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_notusediscount', "Don\'t use coupons", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_morediscount', "more coupons", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paiderror', "Payment failture", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paidok', "paid successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_beingpaid', "paying...", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_scanpayment', "Wechat scan", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_invoicehead', "Enter invoice title", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_topaynow', "Pay now", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order', "Order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_noopaccess', "You don\'t have permission to operate this order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_errornopay', "System error,can\'t pay", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_passno', "Password error", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_payok', "Paid successfully!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund', "Refunding…", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund_tips1', "The order contain virtual item,can\'t be canceled", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_precmoney', "Enter amount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nosckpce', "Item you ordered is out of stock or exceeded purchase limit!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_noaccess', "You have no permission to view this order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_del', "Delete", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_lowpurchase', "Item you ordered is exceeded purchase limit!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_lowstocks', "Item you ordered is out of stock!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_success', "operation successful", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_delok', "Deleted successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_saveok', "Saved successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_error', "Data error", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_ordercenter', "Order center", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_rechargemoney', "Amount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_reason', "Cause", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_money', "amount of money", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_time', "Time", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_accountrecharge', "Recharge", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_modifyinfo', "Modify personal information", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_consumer', "Consumer details", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_allorders', "view all orders", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_balance', "Account Balance", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_save', "save", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_consigneeaddress', "Details address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_consigneetel', "Receiver phone number", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_consigneename', "receiver name", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cancelorderok', "Be sure to cancel order?", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paid', "Payment amount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_modifyprice', "Price increase / reduction", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discount', "Discount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freight', "Freight", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_messageabbr', "Buyer message", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_express', "Shipping by express", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_logisticsinfo', "logistics information", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nologistics', "Needn\'t to shipping", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_complete', "complete", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_deliver', "Shipping", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_payment', "pay", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_placeorderabbr', "order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cancelorder', "Cancel order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_noorders', "No order that meet the requirements", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_topay', "Go to pay", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_orderamount', "order amount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_moreorder', "more", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_commodityname', "Item name", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_closed', "Closed", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receipt', "Waiting for receipt", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_bepaid', "waiting for payment", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_allvalidorders', "all valid orders", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_loginpassword', "Login password", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paybalance', "pay with account balance", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymod', "Choose below the payment method to pay", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paytotal', "Total amount payable", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receiving', "Receipt information", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_orderdetails', "Order details", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_ordernumber', "Order number", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_pleasepayment', "Complete payment, cancel the order if timeout", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_please', "please", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_ordersuccess', "Submitted successfully! Go to pay", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_freefreight', "Free shipping", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_pleaseaddress', "Set receipt address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_placeorder', "Submit Order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_message', "leave a message for merchant", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_return', "go back", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_invoicecontent', "Invoice content", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_need', "need", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_unwanted', "No need", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_invoice', "Invoice", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_delivery', "Shipping method", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentcod', "pay when receiving item", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentonline', "Pay online", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_paymentmod', "Payment method", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_addto', "Add", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_address', "Receipt address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_oos', "No stock", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_errorrefresh', "Data error,please refresh page", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_operation', "operation", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_subtotal', "subtotal", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_price', "price", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_deleteok', "Be sure to delete it?", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cancel', "Cancel", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_ok', "Yes", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goshopping', "go to shopping", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_gosettlementabbr', "go to checkout", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_total', "total", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_checkall', "Select all", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_moregoods', "Customers who bought this item also bought", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_continue', "go to shopping", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_tocartok', "Successful!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_gosettlement', "go to cart page to checkout", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_intotal', "total", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_commodity', "Item", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cart', "Cart", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_mycart', "My cart", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_out', "quit", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_settings', "Account settings", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_myorder', "My order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_personal', "Mall center", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_login', "Log in", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_register', "Register", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_emptycart', "No item in cart", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_recommend', "Hot recommend", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_details', "Item details", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_tocart', "add to cart", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_buyimmediately', "Buy now", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_number', "quantity", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_purchase', "Each person only can buy", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_piece', "Piece", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_stock', "Stock", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_original', "Original price", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_doreceipt', "confirm receipt", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_doreceipt_if', "Do you confirm that you received it?", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_allusers', "All member", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_exceeduser', "get", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_userange', "range of use", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_allgoods', "All items", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_selectgoods', "designated Items", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_express_noopen', "Haven\'t open inquiry function", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_finance_in', "Income", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_finance_out', "Expenditure", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_goods_noquery', "Temporarily haven\'t open query function", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_company_pay', "pay with company bank card", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_normal_invoice', "Invoice", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_online_invoice', "Electronic invoice", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_tax_invoice', "Vat invoice", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_nogoods', "Refund because of no stock", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund', "Refunding…", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_bedeliver', "Pending", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_over_deliver', "Shipped", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_over', "Completed", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_achieve', "Up to", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_reduce', "off", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_period_validity', "Validity period", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_usetime', "Using time", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_discountvalue', "face value", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_to', "to", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_hour', "hour", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_minute', "minute", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_online', "Order online", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_havepay', "This order has been paid or closed !", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_payinsufficient', "Your balance is not enough. Click this link to recharge!", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receiveemail', "Receiving mailbox", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receiveemail_prompt', "Used to receive account information", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_instructions', "Instructions", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_clickview', "more", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_searchfail', "Query failture,please contact webmaster", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_needlogin', "Log in", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_buy', "Buy", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_myfavorite', "My favorites", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_mydiscount', "My coupons", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_myaddress', "Receipt address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_logistics_schedule', "Logistics progress", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_choosepara', "Select the full option", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_lowstocks_min', "No enough stock", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_creditcode', "Enter a credit code", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_payinterface_error', "Payment interface error,please contact webmaster", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_pay_type_off', "The merchant has not opened any payment method", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund_reason', "reason of return and exchange", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_cancel_reason', "reason of canceling order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_reason_detail', "Reason details", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund_converse', "message record about return", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_echo', "reply", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_leaving_message', "Leave a message", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_select_cancel_reason', "Select a reason of canceling order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_refund_refund_reason', "Select a reason of return and exchange", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_cancel', "Cancel order", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refund', "apply for return and exchange", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_refunding', "Return and exchange", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_gain_fail', "Failture", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_card_gain_success', "Get successfully", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_free', "Buy any item,money off", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_free_tips1', "Up to", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_free_tips2', "pieces，off", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content1', "congratulations that you become", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content2', "new member，and thank you for", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content3', "Attention and support and welcome to use our products and services", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content4', "Login address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content5', "Login account", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_content6', "Login password", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_email_title', "Automatically register for an account and password", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_by_type1', "Integrated sort", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_by_type2', "Sales", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_by_type3', "Price", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_img_upload', "Upload picture", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_disc_man', "Up to", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_disc_jian', "Piece", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_disc_zhe', "Discount", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_disc_orderfree', "User buy any item,money off", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_card', "Shipping codes", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_order_extracting_code', "Extract shipping code", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_no_address', "No receipt address,please add it", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_adminstrator', "Administrator", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_receive_albe', "vaild", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_title', "You have new order,please check it on background", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row1', "Address", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row2', "Order number", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row3', "Item", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row4', "Price", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row5', "User name", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_remind_row6', "Phone number", 0, 0, 1, 10043, 'en');
INSERT INTO met_language VALUES (null, 'app_shop_click_show_detail', "More", 0, 0, 1, 10043, 'en');
