<?php
$dllist=array (
  0 => 'dllist.php',
  1 => 'install.class.php',
  2 => 'file/app/app/temtool/admin/class/inc.class.php',
  3 => 'file/app/app/temtool/admin/class/tem.class.php',
  4 => 'file/app/app/temtool/admin/file/install.class.php',
  5 => 'file/app/app/temtool/admin/setedit.class.php',
  6 => 'file/app/app/temtool/admin/templates/css/metinfo.css',
  7 => 'file/app/app/temtool/admin/templates/js/jquery.dragsort-0.5.2.min.js',
  8 => 'file/app/app/temtool/admin/templates/js/own.js',
  9 => 'file/app/app/temtool/admin/templates/remodal/jquery.remodal.css',
  10 => 'file/app/app/temtool/admin/templates/remodal/jquery.remodal.min.js',
  11 => 'file/app/app/temtool/admin/templates/setedit.php',
  12 => 'file/app/app/temtool/admin/templates/temin.php',
  13 => 'file/app/app/temtool/admin/templates/temlist.php',
  14 => 'file/app/app/temtool/admin/templates/temset.php',
  15 => 'file/app/app/temtool/admin/templates/temsetlist.php',
  16 => 'file/app/app/temtool/admin/templates/tools.php',
  17 => 'file/app/app/temtool/admin/templates/word.php',
  18 => 'file/app/app/temtool/admin/temset.class.php',
  19 => 'file/app/app/temtool/admin/temtool.class.php',
  20 => 'file/app/app/temtool/admin/tmp/install.class.php',
  21 => 'file/app/app/temtool/admin/uninstall.class.php',
  22 => 'file/app/app/temtool/icon.png',
);
?>