##JS lang
INSERT INTO met_language VALUES (null, 'pay_precmoney', "Enter recharge amount!", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_payinterface_error', "Payment interface error, please contact webmaster", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paidok', "Paid successfully!", 0, 0, 1, 10080, 'en');
##
INSERT INTO met_language VALUES (null, 'pay_recharge', "Account recharge", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_time', "Time", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_price', "Amount", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_balance', "Account balance", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_reason', "Cause", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_dopay', "Go to pay", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_order', "Order", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_payment', "Pay", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_passno', "Password error", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_subject', "Product name", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_input_amoun', "Enter recharge amount", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_amount', "Recharge amount", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_ordersuccess', "Submitted successfully,go to pay", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_please', "Please~", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pleasepayment', "pay for the order ,close the order once time out", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_ordernumber', "Order number", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_orderdetails', "Order details", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_receiving', "receipt information", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_commodity', "Product", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_beingpaid', "Paying...", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paytotal', "Amount payable", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paytotal', "Amount payable", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_invoice', "Invoice", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_scanpayment', "WeChat scans", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paiderror', "Payment faillure", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paidok', "Paid successfully!", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_balancepay', "Balance payment", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_ok', "Yes", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paysuccess', "Paid successfully", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_payfailed', "Payment faillure", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_consumption_detail', "Consumer records", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_accountrecharge', "Recharge", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_order_pay', "Order payment", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_clse_tips', "Online payment has not been activated, please contact the merchant", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_required_para_missing', "Missing required parameters", 0, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paymentok_title', "Ordered successfully", 0, 0, 0, 10080, 'en');
##pay_type
INSERT INTO met_language VALUES (null, 'pay_pay_type0', "Pay by account balance", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type1', "WeChat scans", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type2', "Alipay WAP", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type3', "Alipay website", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type4', "UnionPay B2C", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type5', "PayPal", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type6', "Wechat public account", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type7', "WeChat H5", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type8', "Reserved interface", 0, 0, 1, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_pay_type9', "UnionPay B2B", 0, 0, 1, 10080, 'en');
