INSERT INTO met_language VALUES (null, 'cancel', "Cancel", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'time', "Time", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_payswitch', "Payment switch", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'payapi', "Payment Interface Management", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_new', "New", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_course', "Course", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_merchantid', "Merchant number", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_financialdeta', "Transaction Records", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_management', "System Configuration", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_apimanage', "Interface Management", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxpay', "Wechat pay", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipaywappay', "Alipay wap", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay', "Alipay", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upayb2c', "UnionPay B2C", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upayb2b', "UnionPay B2B", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_basiccongi', "General information settings", 1, 0, 0, 10080, 'en');
##weixinpay
INSERT INTO met_language VALUES (null, 'pay_wxscan', "WeChat scans", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxJsApiPay', "WeChat public account ID", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxh5', "Wechat phone H5", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxapp_id', "Pulic account ID", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxapp_mchid', "Merchant number", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxapp_key', "Merchant payment private key", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxapp_secert', "Public account setcert", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips1', "Merchant number", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips2', "Merchant payment private key，set according to the mail (must be configured, log in to the merchant platform to set it )", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips3', "Public account setcert(Only when pay with JSAPI , you need to configure it, log in to the public platform, and enter the developer center to set it)", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips4', "Pay with WeChat public account ,please press", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips5', "Set the authorization directory of  payment interface to", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_wxtips6', "Bind APPID of payment interface (must be configured, can be viewed in the account email)", 1, 0, 0, 10080, 'en');
##alipay
INSERT INTO met_language VALUES (null, 'pay_alipay_oldapiset', "Old Alipay interface configuration", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_app_partner', "Partner ID", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips1', "Partner ID, 16-bit number starting with 2088", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_app_seller_email', "Alipay account for receiving money", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips2', "Alipay account for receiving money", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_app_key', "MD5 private key", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips3', "MD5 private key, 32-bit characters consisting of numbers and letters", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_openset', "Open platform configuration", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_openset_tips1', "Alipay open platform interface", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_openset_tips2', "Your server PHP version is", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_openset_tips3', ",need to upgrade it to 5.0 to 7.0 version", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_openset_tips4', ", your server does not open the openssll extension function. If you do not need Alipay WAP payment, you can only configure the old version of the payment interface.", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips4', "Alipay open platform payment interface requires php5.5 version and above. To use the Alipay wap website function, you need to go to the Alipay merchant platform to apply for and configure this interface", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_private_key', "Alipay merchant private key", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_public_key', "Alipay public key", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips6', "Alipay private key configuration address", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips7', "Alipay Private Key Generation Tool", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_alipay_tips8', "Get Alipay public key", 1, 0, 0, 10080, 'en');
##upay
INSERT INTO met_language VALUES (null, 'pay_upay_merid', "Merchant number", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_cert_path', "Certificate path settings", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_tips1', "Before uploading a certificate, please add \"pfx\" and \"cer\" as \"File format are allowed  to be uploaded\" in \"Security and Efficiency\"", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_tips2', "After this switch is turned on, the test of UnionPay interface will be requested. The UnionPay account will not generate real transactions. This mode is only for testing. Please close it after the website is officially launched, and ensure that all configuration information is the official interface configuration information of UnionPay.", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_tips3', "Before uploading the certificate,go to", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_tips4', "Security and Efficiency", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_tips5', "add \"pfx\" and \"cer\" as \"File format are allowed  to be uploaded\"", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_sign_cert_path', "Merchant private key certificate", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_fpfx', "Upload .pfx file", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_upay_sign_cert_pwd', "Password for signature", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_test_mod', "Test mode", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_aipmodset', "Interface Environment settings", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_aiptype', "Interface", 1, 0, 0, 10080, 'en');
##paypal
INSERT INTO met_language VALUES (null, 'pay_paypal_sandbox', "SandBox Environment（SandBox）", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_live', "Production Environment（Live）", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_liveset', "Production Environment（Live）interface parameters", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_sanboxset', "SandBox Environment（SandBox） interface parameters", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_usermail', "Merchant Mailbox", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_pass', "Merchant password", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_paypal_signature', "Signature", 1, 0, 0, 10080, 'en');
#finance
INSERT INTO met_language VALUES (null, 'pay_finance_in', "Income", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_finance_out', "Expenditure", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_price', "Money", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_nobalance', "Have no enough money", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_nouser', "User doesn\'t exist", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_screen', "Filter", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_till', "to", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_membername', "Member name", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_opuser', "Operator", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_reason', "Cause", 1, 0, 0, 10080, 'en');
##pay
INSERT INTO met_language VALUES (null, 'pay_paysuccess', "Paid successfully", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_payfailed', "Payment failure", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_coinprefix', "Currency Symbol", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_coinsuffix', "Currency Unit", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_tips1', "Payment Reminder in member center", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_tips2', "The user needs to enable a payment method to obtain the parameters firstly,then set it here. Because of the security of the funds, the system does not support the third-party payment interface.", 1, 0, 0, 10080, 'en');
INSERT INTO met_language VALUES (null, 'pay_weixin_help_title', "Developer document about WeChat Pay and Wechat public account payment", 1, 0, 0, 10080, 'en');